### ISSUE TITLE
Формат розширеної відповіді

### ISSUE THREAD

**Issue by kroman0** [openprocurement/openprocurement.integrations.edr#25]
- [x]  founders потрібно привести до стандартизованого виду:
```
founders:
- address:
    countryName: ...
    postalCode: ...
    streetAddress: ...
```

- [x] Не потрібно відображати `additionalActivityKinds: null` при відсутності значення.
